trigger:
- multiple-jobs

variables:
  buildConfiguration: 'Release'

jobs:
- job: WebApp1
  displayName: 'Build WebApp1'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: Build
    displayName: 'Build app1'
    script: echo Building application 1

  - task: Test
    displayName: 'Test'
    scriot: echo Testing the code app1

- job: WebApp2
  displayName: 'Build WebApp2'
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: Build
    displayName: 'Build app2'
    script: echo Building application 2

  - task: Test
    displayName: 'Test'
    scriot: echo Testing the code app2
