trigger:
- master

variables:
  buildConfiguration: 'Release'

jobs:
- job: WebApp1
  displayName: 'Build WebApp1'
  pool:
    vmImage: 'ubuntu-latest'

steps:
- script: echo I am job 1
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo Build Number
    echo '$(Build.BuildNumber)'
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  
- script: npm install terraform -y
  displayName: 'Install terraform'

- job: WebApp2
 - job: WebApp1
  displayName: 'Build WebApp1'
  pool:
    vmImage: 'ubuntu-latest'

steps:
- script: echo I am job 2
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo Build Number
    echo '$(Build.BuildNumber)'
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  
- script: npm install terraform -y
  displayName: 'Install terraform'
