name: 1.0$(Rev:.r)
# simplified trigger (implied branch)
trigger:
  - master
# YAML file in the main branch
#schedules:
#- cron: "0 0 * * *"
variables:
  name: martin
pool:
  vmImage: ubuntu-latest
  
jobs:
- job: helloworld
  steps:
  - script: echo "Hello, $(name)"
